import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider.js"
import { ClerkProvider } from '@clerk/nextjs';
import Navbar from "@/components/Navbar.jsx";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[url('/background.jpg')] bg-cover bg-center min-h-screen backdrop-blur`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystems
          disableTransitionOnChange
        >
          <ClerkProvider>
            <Navbar />
            {children}
          </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}